version: '3'

volumes:
    data:
    notebooks:
    scipt:

services:
    jupyter:
        image: nlp-env:1.1
        # build:
        #     context: .
        container_name: nlp-env-dev
        volumes:
            - ./data:/workdir/data
            - ./notebooks:/workdir/notebooks
            - ./script:/workdir/script
            - ./mecab-ipadic-neologd:/workdir/mecab-ipadic-neologd
        tty: true
        ports:
            - 8888:8888
        command: sh start.sh
